### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Herve-M** [valeraf23/ObjectComparator#2]
Hello,

I didn't see any license on the nuget as in the repository, is it possible to know under which one this project is?

Thanks,
Hervé

**Comment by valeraf23** [comment]
Hello,
Currently, I have no license 
Why you are asking about it?

**Comment by cal5barton** [comment]
Need to know how permissive this open source license is in order to use it in a commercial setting or any other setting. https://choosealicense.com/ @valeraf23  can you please provide a [github license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) so others know how we can use this library?

**Comment by valeraf23** [comment]
The license was provided
Apache License 2.0

ср, 24 авг. 2022 г. в 23:08, Callen Barton ***@***.***>:

**Comment by valeraf23** [comment]
The license was provided
Apache License 2.0
